server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/document_mgmt
    username: dev
    password: devpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # You can set this to "create" if you want Hibernate to create tables, or "update" to update schema
    show-sql: true       # Set to true if you want to see SQL queries in the console
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
